[[session]]
name = "Dev 📥"
path = "~/Developer"
startup_command = "ls"

[[session]]
name = "dotfiles📁"
path = "~/dotfiles"
[[session]]
name = "tmux config⚒️"
path = "~/dotfiles/"
startup_command = "nvim .tmux.conf"
[[session]]
name = "nvim config ⚒️"
path = "~/dotfiles/.config/nvim/"
startup_command = "nvim"

