[[mgr.prepend_keymap]]
on = ["g", "b"]
run = "cd ~/Developer"
desc = "Cd to ~/Developer"
[[mgr.prepend_keymap]]
on = ["g", "w"]
run = "cd ~/Documents"
desc = "Cd to ~/Developer"
[[mgr.prepend_keymap]]
on = "<C-p>"
run = '''
  shell 'qlmanage -p "$@"'
'''
